apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-flask-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-flask
  template:
    metadata:
      labels:
        app: ai-flask
    spec:
      containers:
      - name: ai-flask-container
        image: ai-flask-app:latest
        imagePullPolicy: Never          # 👈 ADD THIS LINE
        ports:
        - containerPort: 5000

